1:59:06.001] HWID: {244fb994-880e-11eb-be22-806e6f6e6963}
[14-09-2021 || 21:59:06.012] initialization LiquidMod complete
[14-09-2021 || 21:59:06.012] randomization fix
[14-09-2021 || 21:59:06.012] ini loading
[14-09-2021 || 21:59:06.012] Fucking language loaded from fucking ini. Value: 29128432
[14-09-2021 || 21:59:06.022] Loading D:\aagt\ggttaa\LiquidMod\Liquid.ini...
[14-09-2021 || 21:59:06.023] Parse error: item (expected '=')
[14-09-2021 || 21:59:06.023] Parse error:  # (expected '=')
[14-09-2021 || 21:59:06.023] Parse error:  # (expected '=')
[14-09-2021 || 21:59:06.023] Parse error: effect (expected '=')
[14-09-2021 || 21:59:06.023] Unknown setting 'key_fastwarp'
[14-09-2021 || 21:59:06.024] Unknown setting 'adminlist'
[14-09-2021 || 21:59:06.024] Unknown setting 'adminlist'
[14-09-2021 || 21:59:06.024] Unknown setting 'adminlist'
[14-09-2021 || 21:59:06.024] Warning: setting 'language' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'deadmatch_effects' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'helpbox_time' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'menu_speed' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'macross_key' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'macross_tab_key' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'macross_factor' was not present in the .ini file
[14-09-2021 || 21:59:06.024] Warning: setting 'macross_movement_help' was not present in the .ini file
[14-09-2021 